### ISSUE TITLE
Telling xcarve-proxy where to reach xcarve-server

### ISSUE THREAD

**Issue by hjagnew** [adafruit/xcarve-server#2]
Is there some place to configure xcarve-proxy that tells it where to find xcarve-server on the network?

I have disabled the mac driver for Easel, and have xcarve-proxy started on my local machine and I see the listener on port 1338 on my local machine.
I have xcarve-server started on the RPi3 and see the listener on port 1338.

When I start my local copy of Easel, I can see attempts to connect to the local :1338 listener.

I don't see any probing of the network by my workstation to determine where the xcarve-server is running on the network.

**Comment by toddtreece** [comment]
`xcarve-proxy` uses bonjour/mdns to find the pi, and it expects to find  the pi at `xcarve.local`. this handled by the pi finder in the tutorial, but you can set the hostname of your pi to `xcarve` and it should find it after a reboot of your pi.

**Comment by hjagnew** [comment]
That worked, I added the following entry to /etc/hosts on my mac, where X.X.X.X is the IP of the RPi3.

X.X.X.X       xcarve.local xcarve
